# Copyright 2023 UMH Systems GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: Test OPC UA

on:
  workflow_call:

jobs:
  go-test-opcua-unit:
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Run OPC UA Unit Tests
        run: make test-unit-opc

  go-test-opcua-plc:
    runs-on: depot-ubuntu-24.04
    permissions:
      packages: write
      contents: read
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Install Tcping
        run: go install github.com/cloverstd/tcping@v0.1.1
      - name: Check S7 port availability
        id: check_s7
        run: |
          set +x
          URI="${{ secrets.TEST_S7_ENDPOINT_URI }}"
          ENDPOINT="${URI#opc.tcp://}"
          if tcping -c 4 -T 1s "$ENDPOINT" | grep -qi "Connected"; then
            echo "available=false" >> "$GITHUB_OUTPUT" # TODO: Remove this once the plc is available again
            echo "TEST_S7_ENDPOINT_URI=${{ secrets.TEST_S7_ENDPOINT_URI }}" >> "$GITHUB_ENV"
            echo "TEST_S7_FINGERPRINT=${{ secrets.TEST_S7_FINGERPRINT }}" >> "$GITHUB_ENV"
            echo "using s7-main device for testing"
          else
            echo "available=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Check S7-fallback port availability
        id: check_s7_fallback
        if: ${{ steps.check_s7.outputs.available == 'false' }}
        run: |
          set +x
          URI="${{ secrets.TEST_S7_ENDPOINT_URI_FALLBACK }}"
          ENDPOINT="${URI#opc.tcp://}"
          if tcping -c 4 -T 1s "$ENDPOINT" | grep -qi "Connected"; then
            echo "available=true" >> "$GITHUB_OUTPUT"
            echo "TEST_S7_ENDPOINT_URI=${{ secrets.TEST_S7_ENDPOINT_URI_FALLBACK }}" >> "$GITHUB_ENV"
            echo "TEST_S7_FINGERPRINT=${{ secrets.TEST_S7_FINGERPRINT_FALLBACK }}" >> "$GITHUB_ENV"
            echo "using s7-fallback device for testing"
          else
            echo "available=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Check Wago port availability
        id: check_wago
        run: |
          set +x
          URI="${{ secrets.TEST_WAGO_ENDPOINT_URI }}"
          ENDPOINT="${URI#opc.tcp://}"
          if tcping -c 4 -T 1s "$ENDPOINT" | grep -qi "Connected"; then
            echo "available=true" >> "$GITHUB_OUTPUT"
            echo "TEST_WAGO_ENDPOINT_URI=${{ secrets.TEST_WAGO_ENDPOINT_URI }}" >> "$GITHUB_ENV"
            echo "TEST_WAGO_FINGERPRINT=${{ secrets.TEST_WAGO_FINGERPRINT }}" >> "$GITHUB_ENV"
            echo "using wago-main device for testing"
          else
            echo "available=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Check Wago-fallback port availability
        id: check_wago_fallback
        if: ${{ steps.check_wago.outputs.available == 'false' }}
        run: |
          set +x
          URI="${{ secrets.TEST_WAGO_ENDPOINT_URI_FALLBACK }}"
          ENDPOINT="${URI#opc.tcp://}"
          if tcping -c 4 -T 1s "$ENDPOINT" | grep -qi "Connected"; then
            echo "available=true" >> "$GITHUB_OUTPUT"
            echo "TEST_WAGO_ENDPOINT_URI=${{ secrets.TEST_WAGO_ENDPOINT_URI_FALLBACK }}" >> "$GITHUB_ENV"
            echo "TEST_WAGO_FINGERPRINT=${{ secrets.TEST_WAGO_FINGERPRINT_FALLBACK }}" >> "$GITHUB_ENV"
            echo "using wago-fallback device for testing"
          else
            echo "available=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Start docker container for iotedge/opc-plc
        run: |
          OPCSIM_CONTAINER=$(docker run -d --rm -P \
            --hostname localhost \
            mcr.microsoft.com/iotedge/opc-plc:2.12.29 \
            --pn=50000 --autoaccept --sph --sn=100 --sr=10 --st=uint --fn=5 --fr=1 --ft=uint --gn=5 --certdnsnames=localhost --plchostname=localhost --unsecuretransport)
          OPCSIM_PORT=$(docker inspect -f '{{(index (index .NetworkSettings.Ports "50000/tcp") 0).HostPort}}' $OPCSIM_CONTAINER || true)
          #OPCSIM_PORT=$(docker inspect $OPCSIM_CONTAINER | jq '.[].NetworkSettings.Ports["50000/tcp"] | .[0].HostPort' | tr -d '"' || true)
            echo "################# Docker Port ######################"
            echo "Opcsim port: $OPCSIM_PORT"
            if [ -z "$OPCSIM_PORT" ]; then
              echo "Failed to get opcsim port"
              docker inspect $OPCSIM_CONTAINER
              docker stop $OPCSIM_CONTAINER || true
              exit 1
            fi


          echo "################# Docker IP ######################"
          OPCSIM_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $OPCSIM_CONTAINER)
          echo "Opcsim IP: $OPCSIM_IP"

          echo "OPCSIM_CONTAINER=$OPCSIM_CONTAINER" >> $GITHUB_ENV
          echo "OPCSIM_IP=$OPCSIM_IP" >> $GITHUB_ENV
          echo "OPCSIM_PORT=$OPCSIM_PORT" >> $GITHUB_ENV

      - name: Debug container status
        run: |
          docker ps
          docker logs $(docker ps -q -f ancestor=mcr.microsoft.com/iotedge/opc-plc:2.12.29)

      - name: Test container availability
        run: |
          tcping 127.0.0.1:$OPCSIM_PORT

      - name: Test OPC Simulator
        env:
          TEST_OPCSIM_PORT: ${{ env.OPCSIM_PORT }}
          TEST_OPCUA_SIMULATOR: true
          TEST_OPCUA_WRITE_SIMULATOR: true
        run: make test-integration-opc

      - name: Test WAGO
        env:
          TEST_WAGO_USERNAME: ${{ secrets.TEST_WAGO_USERNAME }}
          TEST_WAGO_PASSWORD: ${{ secrets.TEST_WAGO_PASSWORD }}
        run: |
          if [ -z "$TEST_WAGO_ENDPOINT_URI" ]; then
            echo "no wago-endpoint available for testing"
            exit 1
          fi
          make test-integration-opc

      - name: Test S7
        run: |
          if [ -z "$TEST_S7_ENDPOINT_URI" ]; then
            echo "no s7-endpoint available for testing"
            exit 1
          fi
          make test-integration-opc

      - name: Cleanup docker containers
        if: always()
        run: |
          docker stop $OPCSIM_CONTAINER || true
          docker ps
  go-test-kepware-plc:
    needs: [go-test-opcua-plc]
    runs-on: depot-ubuntu-24.04
    permissions:
      packages: write
      contents: read
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Install Tcping
        run: go install github.com/cloverstd/tcping@v0.1.1

      - name: Check Kepware port availability
        id: check_kepware
        run: |
          set +x
          CURRENT_MINUTE=$(date +%M)
          CURRENT_HOUR=$(date +%H)

          # make timecheck since we restart kepware-runtime every 2 hours and
          # don't want to unneccessaryly fail here
          if [ "$CURRENT_MINUTE" -eq "00" ] && [ $((10#$CURRENT_HOUR % 2)) -eq 0 ]; then
            sleep 60
          fi

          URI="${{ secrets.TEST_KEPWARE_ENDPOINT }}"
          ENDPOINT="${URI#opc.tcp://}"
          if tcping -c 4 -T 1s "$ENDPOINT" | grep -qi "Connected"; then
            echo "available=true" >> "$GITHUB_OUTPUT"
            echo "TEST_KEPWARE_ENDPOINT=${{ secrets.TEST_KEPWARE_ENDPOINT }}" >> "$GITHUB_ENV"
            echo "TEST_KEPWARE_FINGERPRINT=${{ secrets.TEST_KEPWARE_FINGERPRINT }}" >> "$GITHUB_ENV"
            echo "using kepware for testing"
          else
            echo "available=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Test
        env:
          TEST_KEPWARE_USERNAME: ${{ secrets.TEST_KEPWARE_USERNAME }}
          TEST_KEPWARE_PASSWORD: ${{ secrets.TEST_KEPWARE_PASSWORD }}
        run: |
          if [ -z "$TEST_KEPWARE_ENDPOINT" ]; then
            echo "no kepware-endpoint available for testing"
            exit 1
          fi
          make test-integration-opc
